apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.servicePort }}